### ISSUE TITLE
segfault at startup

### ISSUE THREAD

**Issue by fare** [cymonsgames/ASCIIpOrtal#23]
I compiled ASCIIpOrtal with either make linux or make nosdl, and the result is the same: segfault at startup. ltrace tells me these are the last calls before segfault:
```
_ZNSt13basic_filebufIcSt11char_traitsIcEE5closeEv(0x7ffdbed22250, 0, 0x7fea9493cca0, 0x55f97936d010) = 0
_ZNSt12__basic_fileIcED1Ev(0x7ffdbed222b8, 0, 0x7fea9493cca0, 0x55f97936d010) = 0
_ZNSt6localeD1Ev(0x7ffdbed22288, 0, 0x7fea9493cca0, 0x55f97936d010) = 0x7fea94c7a5f8
_ZNSt8ios_baseD2Ev(0x7ffdbed22340, 0, 0x7fea9493cca0, 0x7fea94c72f18) = 0x7fea94c7a5f8
--- SIGSEGV (Segmentation fault) ---
```
Running on Debian Linux testing on x64.

**Comment by gissf1** [comment]
I'm also experiencing a similar issue with segfaults on startup.  It used to work just fine, but that was probably a couple years ago.  My system is running Manjaro / Arch.  Compiling with debug symbols via makepkg, and running in GDB I get the following backtrace:

> (gdb) r
> Program received signal SIGILL, Illegal instruction.
> 0x000055555556893a in MapPack::set_currentlevel(int) ()
> (gdb) bt
> #0  0x000055555556893a in MapPack::set_currentlevel(int) ()
> #1  0x0000555555567d52 in MapPack::MapPack(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
> #2  0x00005555555885e1 in main ()

It seems plausible that the pull request in #25 may fix this behavior.  @cymonsgames are you considering merging it?

That said, it seems this code hasn't been updated in 5 years, perhaps it's abandoned now?
